### ISSUE TITLE
make true polyfill

### ISSUE THREAD

**Issue by kellyselden** [workmanw/ember-string-ishtmlsafe-polyfill#1]
I suggest mimicking https://github.com/rwjblue/ember-getowner-polyfill/pull/6 so that `Ember.String.isHTMLSafe` is the location of the polyfill instead of the import.

**Comment by workmanw** [comment]
@kellyselden That had occurred to me. I can definitely do that. One curiosity is how do you envision this kind of thing working with the new Javascript Modules API? I mean, obviously if you're using that in your app, you're a version of ember where you don't need this polyfill. Just trying to imagine if there is any impact for addons trying to be backwards compatible.

**Comment by kellyselden** [comment]
I talked this out and slack, and I believe in the future you could both polyfill `Ember.String` and support the modules API. You would have to move the polyfill logic to build time instead of runtime. Then use `ember-cli-version-checker` to include the file that polyfills for older versions. That way you don't run any `import Ember from 'ember';` in the new setup so you can keep in line with tree-shaking.

**Comment by rwjblue** [comment]
@workmanw - The idea is roughly the same as what I did in ember-getowner-polyfill, noop on versions of Ember where the polyfill is not needed.

**Comment by Panman82** [comment]
Just as another reference, `ember-assign-polyfill` recently did the same thing; https://github.com/shipshapecode/ember-assign-polyfill/pull/4

**Comment by workmanw** [comment]
@Panman8201 @kellyselden @rwjblue Thanks for all the info! I'm going to try to make sometime in the coming weeks to convert this addon. I've been slammed with work and trying maintain other addons.

**Comment by Panman82** [comment]
FYI, I'm working on this and bringing the addon up-to-date with ember-cli & such. As for the testing scenarios, do you want to test up-to 2.8 (when `isHTMLSafe()` was added) or everything after 1.10 (currently the earliest scenario), including beta/canary?

**Comment by rwjblue** [comment]
I believe we should continue to test 2.8 + current release at least.  Mostly to ensure our polyfill works properly (e.g. folks including it should not have to care about Ember version).

**Comment by workmanw** [comment]
>  I'm working on this and bringing the addon up-to-date with ember-cli & such.

@Panman8201 Thank you very much!!! It's been on my list to do this, but I just haven't gotten to it. 

I'm 👍  on 1.10 - 2.8 + current lease. Might also add 2.12 LTS when it ships. The tests for this are pretty minimal.

**Comment by Panman82** [comment]
Done, except for one question. Should the `import isHTMLSafe from 'ember-string-ishtmlsafe-polyfill';` way of doing it be tested yet? Currently I am, along with testing the "new/native" way of just using `Ember.String.isHTMLSafe()`, but it produces a depreciation message in the test runs. (Not that it's a big deal...)

`addon/index.js` now looks just like https://github.com/rwjblue/ember-getowner-polyfill/blob/v1.2.2/addon/index.js

**Comment by workmanw** [comment]
@Panman8201 Pinged me in slack and I missed it. I think that sounds fine! I've been working on `ember-qunit-assert-helpers` that makes it possible to test for deprecations. In a future version of that addon, it will also suppress expected deprecations. So let's not let that hold this up. I'd say submit a PR.
