### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by bartocc** [workmanw/ember-string-ishtmlsafe-polyfill#11]
#10 fixed the ember-cli-version-checker warning under Ember 2.18+.

ember-awesome-macros depends on ember-string-ishtmlsafe-polyfill@^2.0.0 and a new release would allow ember-awesome-macros, among others probably, to get rid of this warning as well.

See [ ember-awesome-macros issue #452](https://github.com/kellyselden/ember-awesome-macros/issues/452#issuecomment-374657809)

**Comment by bartocc** [comment]
thanks

**Comment by workmanw** [comment]
@bartocc No problem. Sorry about the delay.
