### ISSUE TITLE
Help other addons update to native polyfill

### ISSUE THREAD

**Issue by workmanw** [workmanw/ember-string-ishtmlsafe-polyfill#5]
https://github.com/workmanw/ember-string-ishtmlsafe-polyfill

According to Ember Observer here are the addons using this polyfill. Let's get them all update!

- [X] ~[ember-advanced-combobox](https://github.com/AnnotationSro/ember-advanced-combobox) -- PR: https://github.com/AnnotationSro/ember-advanced-combobox/pull/1~
- [X] ~[ember-advanced-validations](https://github.com/AnnotationSro/ember-advanced-validations) -- PR: https://github.com/AnnotationSro/ember-advanced-validations/pull/1~
- [X] ~[ember-awesome-macros](https://github.com/kellyselden/ember-awesome-macros) -- PR: https://github.com/kellyselden/ember-awesome-macros/pull/256~
- [X] ~[ember-cli-csp-style](https://github.com/BryanCrotaz/ember-cli-csp-style) -- PR: https://github.com/BryanCrotaz/ember-cli-csp-style/pull/6~
- [X] ~[ember-cli-tooltipster](https://github.com/altrim/ember-cli-tooltipster) -- PR: https://github.com/altrim/ember-cli-tooltipster/pull/38~
- [X] ~[ember-cp-validations](https://github.com/offirgolan/ember-cp-validations) -- PR: https://github.com/offirgolan/ember-cp-validations/pull/459~
- [x] [ember-emojione](https://github.com/deveo/ember-emojione)
  - [x] `ember-emojione` relies on `ember-cli-shims` for imports. Need to add `isHTMLSafe` to `ember-cli-shims` and get a new release cut first. -- PR: https://github.com/ember-cli/ember-cli-shims/pull/93
- [X] ~[ember-froala-editor](https://github.com/froala/ember-froala-editor)~
- [X] ~[ember-i18n](https://github.com/jamesarosen/ember-i18n) -- PR: https://github.com/jamesarosen/ember-i18n/pull/441~
- [X] ~[ember-notify](https://github.com/aexmachina/ember-notify) -- PR: https://github.com/aexmachina/ember-notify/pull/107~
- [X] ~[ember-semantic-ui-dropdown](https://github.com/sumn2u/ember-semantic-ui-dropdown) -- PR: https://github.com/sumn2u/ember-semantic-ui-dropdown/pull/5~
- [X] ~[ember-validator](https://github.com/anandts88/ember-validator) -- PR: https://github.com/anandts88/ember-validator/pull/16~
- [X] ~[Semantic-UI-Ember](https://github.com/Semantic-Org/Semantic-UI-Ember) -- PR: https://github.com/Semantic-Org/Semantic-UI-Ember/pull/183~

Checked -> PR Submitted
Stricken -> PR Merged

I'll work over the next few days to submit PRs to all of these.

**Comment by Panman82** [comment]
FYI, ember-froala-editor is done. I updated that within the hour you published the new version. 😃  https://github.com/froala/ember-froala-editor/commit/8103cb8c6af9fcc3d3d21b596bc0cc7eda40497a

**Comment by workmanw** [comment]
You're a machine! 💯

**Comment by rwjblue** [comment]
:heart: for proactively updating downstream addons

**Comment by locks** [comment]
@workmanw ember-i18n and Semantic-UI-Ember are merged!

**Comment by workmanw** [comment]
@locks Thanks!!

**Comment by Turbo87** [comment]
submitted https://github.com/Deveo/ember-emojione/pull/47 to work around the `ember-emojione` import issue mentioned above

**Comment by workmanw** [comment]
Thanks everyone!!!
