### ISSUE TITLE
DEPRECATION: An addon is trying to access project.nodeModulesPath

### ISSUE THREAD

**Issue by tarponjargon** [workmanw/ember-string-ishtmlsafe-polyfill#8]
I opened an issue with ember-cp-validations, but they pointed me here. 

`DEPRECATION: An addon is trying to access project.nodeModulesPath. This is not a reliable way to discover npm modules. Instead, consider doing: require("resolve").sync(something, { basedir: project.root }). Accessed from: NPMDependencyVersionChecker (/Users/rory/Desktop/ember-quickstart/node_modules/ember-string-ishtmlsafe-polyfill/node_modules/ember-cli-version-checker/src/npm-dependency-version-checker.js:11:32)`

[https://github.com/offirgolan/ember-cp-validations/issues/562#issuecomment-364617752](https://github.com/offirgolan/ember-cp-validations/issues/562#issuecomment-364617752)

**Comment by oskarrough** [comment]
Is the fix to upgrade `ember-cli-version-checker`?

Edit: tried upgrading it to 2.1.0 but tests wouldn't start afterwards.
